# Site
repository: derylong.github.io
favicon: images/saturn_104926_Nk7_icon.ico

# Content configuration version
version: 2

# Personal info
name: Deryl Long
title: Astronomy PhD Candidate
email: del6h@virginia.edu
website: derylong.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  derylong
orcid_username: 0000-0003-3840-7490

# Additional icon links
additional_links:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Deryl (she/they) and I'm a 3rd year PhD student in the Department of Astronomy at [UVA](https://astronomy.as.virginia.edu/).
  I work with the [Cleeves Group](https://www.astrocleeves.group/home) to study the physical and
  chemical conditions under which planet formation occurs. Through my research I seek to provide critical linkages between protoplanetary disks and
  the exoplanetary systems that are ultimately formed in these environments.

  I use ALMA observations and 2D chemical models to constrain properties of protoplanetary disks such as ionization, which governs chemical
  and dynamical processes related to planet formation.

content:
  - title: Research # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Protoplanetary Disk Ionization
        description: |
          ionization is important :) trust me

      - layout: top-middle
        title: Planet Formation on Solar System Scales
        description: |
          my paper


# Footer
footer_show_references: false
#references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
