# Site
repository: derylong.github.io
favicon: images/saturn_104926_Nk7_icon.ico

# Content configuration version
version: 2

# Personal info
name: Deryl Long
title: Astronomy PhD Candidate
email: del6h@virginia.edu
website: derylong.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  derylong
orcid_username: 0000-0003-3840-7490

# Additional icon links
additional_links:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Deryl (she/they) and I'm a 4th year PhD student in the Department of Astronomy at [UVA](https://astronomy.as.virginia.edu/).
  I work with the [Cleeves Group](https://www.astrocleeves.group/home) to study the physical and
  chemical conditions related to planet formation. Through my research I seek to provide critical linkages between protoplanetary disks and
  the exoplanetary systems that are formed in these environments. You can view my full CV [here](https://nbviewer.org/github/derylong/derylong.github.io/blob/main/images/deryl_cv_22.pdf).


content:
  - title: Research # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Protoplanetary Disk Ionization
        description: |
          Ionization drives important chemical and dynamical processes within protoplanetary disks, including the formation of organics and water and the transport of material throughout the disk
          via accretion and magneto-hydrodynamics (MHD). Despite its importance, the amount of ionization and its distribution is still a key piece of the planet formation puzzle that has yet to be solved.
          My current research aims to bridge this gap by providing the most sensitive constraints on ionization in protoplanetary disks to date
          using ALMA observations and 2D chemical models. Stay tuned for forthcoming results!

      - layout: top-middle
        title: Planet Formation on Solar System Scales
        description: |
          Surveys of protoplanetary disks such as [DSHARP](https://almascience.eso.org/almadata/lp/DSHARP/) reveal a diversity of substructure. These surveys have mainly
          targeted massive disks, while the majority of protoplanetary disks are much smaller. To investigate the presence of substructure on Solar System scales
          I looked at high resolution ALMA observations of the compact GQ Lup dust disk. My results hint at a [rich world of
          substructures in small disks](https://ui.adsabs.harvard.edu/abs/2020ApJ...895L..46L/abstract), which may be related to young forming planets. A [subsequent analysis of compact sources in Taurus](https://arxiv.org/abs/2305.03862)
          reveals substructure in half of the disks and finds that occurence rates for inferred planets are consistent with microlensing and direct-imaging surveys (Zhang et al. 2023).


# Footer
footer_show_references: false
#references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
